# name: CI

# on: [push]

# jobs:
#   build:

#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v1
#     - name: Run a one-line script
#       run: echo Hello, world!
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.

name: NPM release Build and Publish

on:
  push:
      branches:
      - master
      - release/*

jobs:
  shellLint:
    name: Shell Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Shell Lint
      uses: actions/bin/shellcheck@master
      with:
        args: entrypoint.sh
    - name: Build Docker
      uses: actions/docker/cli@master
      with:
        args: build -t npm .
    - name: Build
      uses: actions/npm@master
      with:
        args: install
    - name: Test
      uses: actions/npm@master
      with:
        args: test
    - name: Publish Filter
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Publish
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
